apiVersion: v1
kind: Pod
metadata:
  name: test-pvc-pod
  namespace: default
spec:
  containers:
    - name: test-pvc
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "success" > /data/$(date +%Y-%m-%d_%H-%M-%S).txt
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: s3-pvc