    apiVersion: v1
    kind: Service
    metadata:
      name: web
      namespace: homework
    spec:
      ports:
      - port: 80
        targetPort: 80
        protocol: TCP
      selector:
        app: web
      type: ClusterIP