apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otus
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Otus homework project

  sourceRepos:
  - '*'

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding


  

  destinations:
  - namespace: homework
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: homeworkhelm
    server: https://kubernetes.default.svc
    name: in-cluster
  orphanedResources:
    warn: false
  #  jwtTokens:
  #  - iat: 1535390316

  syncWindows:
  - kind: allow
    schedule: '* * * * *'

  permitOnlyProjectScopedClusters: false

  sourceNamespaces:
  - "argo"