apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: homework
data:
  test: "true"
  default.conf: |
    server {
          listen 8000;
          server_name  _;
          location / {
              root   /homework;
              index  index.html;
            }
    }
    