    apiVersion: v1
    kind: Service
    metadata:
      name: web
      namespace: homework
    spec:
      ports:
      - port: 8000
        targetPort: 8000
        protocol: TCP
      selector:
        app: web
      type: ClusterIP