---
# Kubernetes dashboard
# RBAC required. see docs/getting-started.md for access details.
dashboard_enabled: false

# Helm deployment
helm_enabled: true

# Registry deployment
registry_enabled: false
# registry_namespace: kube-system
# registry_storage_class: ""
# registry_disk_size: "10Gi"

# Metrics Server deployment
metrics_server_enabled: false


# Rancher Local Path Provisioner
local_path_provisioner_enabled: false


# Local volume provisioner deployment
local_volume_provisioner_enabled: false


# CephFS provisioner deployment
cephfs_provisioner_enabled: false


# RBD provisioner deployment
rbd_provisioner_enabled: false


# Gateway API CRDs
gateway_api_enabled: false
# gateway_api_experimental_channel: false

# Nginx ingress controller deployment
ingress_nginx_enabled: false


# ALB ingress controller deployment
ingress_alb_enabled: false


# Cert manager deployment
cert_manager_enabled: false

# MetalLB deployment
metallb_enabled: false


argocd_enabled: false

# Kube VIP
kube_vip_enabled: false


# Node Feature Discovery
node_feature_discovery_enabled: false

